// The Number will be the next sequential TD number of the form HCDxxxx starting with HCD0001
// The Title will be the title of the GitHub Issue that was generated for this problem, question, etc. that resulted in this TD being generated
= HCD0008 - Clarification on applicability of tests 3 and 4 for FDP_DSK_EXT.1 Protection of Data on Disk
:showtitle:
:imagesdir: images
:icons: font
// revnumber and revdate should be the number and date of the revision of this version of the TD
:revnumber: 1
:revdate: 2024-02-05
:linkattrs:

:iTC-longname: Hardcopy Device
:iTC-shortname: HCD-iTC
:iTC-email: iTC-HCD@niap-ccevs.org
:iTC-website: https://hcd-iTC.github.io/
// Provide the link here to either the HCD cPP and/or the HCD SD as applicable
:iTC-GitHub: https://github.com/HCD-iTC/cPP/

Version: {revnumber}, Published: {revdate}

== Impacted Documents

CPP_HCD_V1.0_supporting_doc

// Reference the applicable Section/paragraph number for the HCD cPP SFR(s) / SARs or HCD SD Assurace Activities that this TD pertains to
== References

FDP_DSK_EXT Extended: Protection of Data on Disk

// Provide the issue description extracted from the Issue that was generated for this problem, question, etc. that resulted in this TD being generated.
// Include the Issue Number
== Issue Description

Tests 3 and 4 for FDP_DSK_EXT.1 Protection of Data on Disk are only applicable when the ST author claims FPT_WIPE_EXT.1 Data Wiping. 

// Provide the resolution agreed upon by the HIT for this Issue
== Resolution

Update tests 3 and 4 for FDP_DSK_EXT.1 Protection of Data on Disk to clarify the tests are only applicable when the ST author claims FPT_WIPE_EXT.1 Data Wiping.


// Provide here the specific change(s) by Document, Section number, paragraph and line that is to be made to the HCD cPP and/or HCD SD to resolve this issue
== CPP_HCD_V1.0_supporting_doc

The SD is updated as follows (yellow highlights for additions, strikethrough for deletions) per section that is being updated:

*3.1.3.4. Tests*

The evaluator shall perform the following tests:

Test 1. Write data to Storage device: Perform writing to the storage device with operating TSFI
which enforce write process of User documents and Confidential TSF data.

Test 2. Confirm that written data are encrypted: Verify there are no plaintext data present in the
encrypted range written by Test 1; and, verify that the data can be decrypted by proper key and key
material.

All TSFIs for writing User Document Data and Confidential TSF data should be tested by above Test
1 and Test 2.

Test 3. +++<del>(If data other than D.USER.DOC and D.TSF.CONF are encrypted,) write</del>+++ #[Conditional: If the ST author claims FPT_WIPE_EXT.1 with cryptographic erase, and if data other than D.USER.DOC and D.TSF.CONF are encrypted] Write# the data to the storage
device with operating TSFI which enforce write process of the data.

Test 4. +++<del>(If data other than D.USER.DOC and D.TSF.CONF are encrypted,) verify</del>+++ #[Conditional: If the ST author claims FPT_WIPE_EXT.1 with cryptographic erase, and if data other than D.USER.DOC and D.TSF.CONF are encrypted] Verify# that the data written in Test 3 is not in plaintext form; and verify that the data can be decrypted by proper key and key
material.

//Include a pointer to the file that contains the actual fix for this TD
== Tracking

link:https://github.com/HCD-iTC/HCD-IT/issues/21[Issue #21]
