// The Number will be the next sequential TD number of the form HCDxxxx starting with HCD0001
// The Title will be the title of the GitHub Issue that was generated for this problem, question, etc. that resulted in this TD being generated
= HCD0015: FCS_IPSC_EXT.1.10 – Remove TSS assurance activities from the Tests section
:showtitle:
:imagesdir: images
:icons: font
// revnumber and revdate should be the number and date of the revision of this version of the TD
:revnumber: 1
:revdate: 2025-11-02
:linkattrs:

:iTC-longname: Hardcopy Device
:iTC-shortname: HCD-iTC
:iTC-email: iTC-HCD@niap-ccevs.org
:iTC-website: https://hcd-iTC.github.io/
// Provide the link here to either the HCD cPP and/or the HCD SD as applicable
:iTC-GitHub: https://github.com/HCD-iTC/cPP/

Version: {revnumber}, Published: {revdate}

== Impacted Documents

- CPP_HCD_V1.0e_supporting_doc

// Reference the applicable Section/paragraph number for the HCD cPP SFR(s) / SARs or HCD SD Assurace Activities that this TD pertains to
== References

- FCS_IPSC_EXT.1.10

// Provide the issue description extracted from the Issue that was generated for this problem, question, etc. that resulted in this TD being generated.
// Include the Issue Number
== Issue Description

The Tests section (5.2.1.3.9. FCS_IPSEC_EXT.1.10) includes TSS assurance activities that are misplaced because these activities should be—and are already—located in the TSS section (5.2.1.1.9. FCS_IPSEC_EXT.1.10).

// Provide the resolution agreed upon by the HIT for this Issue
== Resolution

Remove the TSS assurance activities from the Tests section (5.2.1.3.9. FCS_IPSEC_EXT.1.10). 

// Provide here the specific change(s) by Document, Section number, paragraph and line that is to be made to the HCD cPP and/or HCD SD to resolve this issue
== CPP_HCD_V1.0e_supporting_doc

The SD is updated as follows (yellow highlights for additions, strikethrough for deletions) per section that is being updated:

*5.2.1.3.9. FCS_IPSEC_EXT.1.10*

+++<del> Each of the following tests shall be performed for each version of IKE selected in the FCS_IPSEC_EXT.1.5 protocol selection:+++

.. +++<del> Test 1: If the first selection is chosen, the evaluator shall check to ensure that, for each DH group supported, the TSS describes the process for generating each nonce. The evaluator shall verify that the TSS indicates that the random number generated that meets the requirements in this cPP is used, and that the length of the nonces meet the stipulations in the requirement.+++

.. +++<del> Test 2: If the second selection is chosen, the evaluator shall check to ensure that, for each PRF hash supported, the TSS describes the process for generating each nonce. The evaluator shall verify that the TSS indicates that the random number generated that meets the requirements in this cPP is used, and that the length of the nonces meet the stipulations in the requirement.+++

#None.# 

//Include a pointer to the file that contains the actual fix for this TD
== Tracking

link:https://github.com/HCD-iTC/HCD-iTC-Template/issues/360[Issue #360]
